#############################################################################
# Makefile for building: 4830project
# Generated by qmake (2.01a) (Qt 4.7.4) on: Thu Apr 19 18:04:00 2012
# Project:  4830project.pro
# Template: app
# Command: /usr/bin/qmake -o Makefile 4830project.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_WEBKIT
CFLAGS        = -m64 -pipe -g -Wall -W $(DEFINES)
CXXFLAGS      = -m64 -pipe -g -Wall -W $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++-64 -I. -I. -I/usr/local/cuda/include -I/opt/AMDAPP/include -I/usr/include/freetype2
LINK          = g++
LFLAGS        = -m64
LIBS          = $(SUBLIBS)   -lsfml-graphics -lsfml-audio -lsfml-window -lsfml-system -lGLU -lGL -L/usr/lib/nvidia-current -lOpenCL 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = obj/

####### Files

SOURCES       = src/Bitmap.cpp \
		src/Camera.cpp \
		src/CaveNoise.cpp \
		src/Chunk.cpp \
		src/Collision.cpp \
		src/CollisionMesh.cpp \
		src/FrameBuffer.cpp \
		src/Heightmap.cpp \
		src/HeightNoise.cpp \
		src/IEngine.cpp \
		src/ImageLoader.cpp \
		src/main.cpp \
		src/MapGen.cpp \
		src/MeshObject.cpp \
		src/Noise.cpp \
		src/ObjectLoader.cpp \
		src/OCL3DFBMNoise.cpp \
		src/OCLKernel.cpp \
		src/OCLMarchingCubes.cpp \
		src/OCLNoise.cpp \
		src/Perlin.cpp \
		src/Polygonize.cpp \
		src/PostProcess.cpp \
		src/Shader.cpp \
		src/shaderfuncs.cpp \
		src/Text.cpp \
		src/Texture.cpp \
		src/Tree.cpp \
		src/Util.cpp \
		src/Vec3.cpp \
		src/VertexBufferObject.cpp \
		src/VoxelCube.cpp \
		src/Water.cpp \
		src/World.cpp 
OBJECTS       = obj/Bitmap.o \
		obj/Camera.o \
		obj/CaveNoise.o \
		obj/Chunk.o \
		obj/Collision.o \
		obj/CollisionMesh.o \
		obj/FrameBuffer.o \
		obj/Heightmap.o \
		obj/HeightNoise.o \
		obj/IEngine.o \
		obj/ImageLoader.o \
		obj/main.o \
		obj/MapGen.o \
		obj/MeshObject.o \
		obj/Noise.o \
		obj/ObjectLoader.o \
		obj/OCL3DFBMNoise.o \
		obj/OCLKernel.o \
		obj/OCLMarchingCubes.o \
		obj/OCLNoise.o \
		obj/Perlin.o \
		obj/Polygonize.o \
		obj/PostProcess.o \
		obj/Shader.o \
		obj/shaderfuncs.o \
		obj/Text.o \
		obj/Texture.o \
		obj/Tree.o \
		obj/Util.o \
		obj/Vec3.o \
		obj/VertexBufferObject.o \
		obj/VoxelCube.o \
		obj/Water.o \
		obj/World.o
DIST          = /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_phonon.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/debug.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		4830project.pro
QMAKE_TARGET  = 4830project
DESTDIR       = 
TARGET        = 4830project

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: 4830project.pro  /usr/share/qt4/mkspecs/linux-g++-64/qmake.conf /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_phonon.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/debug.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf
	$(QMAKE) -o Makefile 4830project.pro
/usr/share/qt4/mkspecs/common/g++.conf:
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/modules/qt_phonon.pri:
/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/debug.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
qmake:  FORCE
	@$(QMAKE) -o Makefile 4830project.pro

dist: 
	@$(CHK_DIR_EXISTS) obj/4830project1.0.0 || $(MKDIR) obj/4830project1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) obj/4830project1.0.0/ && (cd `dirname obj/4830project1.0.0` && $(TAR) 4830project1.0.0.tar 4830project1.0.0 && $(COMPRESS) 4830project1.0.0.tar) && $(MOVE) `dirname obj/4830project1.0.0`/4830project1.0.0.tar.gz . && $(DEL_FILE) -r obj/4830project1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: 

####### Compile

obj/Bitmap.o: src/Bitmap.cpp src/Bitmap.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/Bitmap.o src/Bitmap.cpp

obj/Camera.o: src/Camera.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/Camera.o src/Camera.cpp

obj/CaveNoise.o: src/CaveNoise.cpp src/CaveNoise.h \
		src/Perlin.h \
		src/VoxelCube.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/CaveNoise.o src/CaveNoise.cpp

obj/Chunk.o: src/Chunk.cpp src/Chunk.h \
		src/MeshObject.h \
		src/Types.h \
		src/Polygonize.h \
		src/VoxelCube.h \
		src/Vec3.h \
		src/MapGen.h \
		src/CaveNoise.h \
		src/Perlin.h \
		src/HeightNoise.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/Chunk.o src/Chunk.cpp

obj/Collision.o: src/Collision.cpp src/Collision.h \
		src/ext/glm/glm.hpp \
		src/ext/glm/core/_fixes.hpp \
		src/ext/glm/core/setup.hpp \
		src/ext/glm/core/_detail.hpp \
		src/ext/glm/core/type.hpp \
		src/ext/glm/core/type_half.hpp \
		src/ext/glm/core/type_half.inl \
		src/ext/glm/core/type_float.hpp \
		src/ext/glm/core/type_int.hpp \
		src/ext/glm/core/type_gentype.hpp \
		src/ext/glm/core/type_size.hpp \
		src/ext/glm/core/type_vec1.hpp \
		src/ext/glm/core/type_vec.hpp \
		src/ext/glm/core/_swizzle.hpp \
		src/ext/glm/core/_swizzle_func.hpp \
		src/ext/glm/core/type_vec1.inl \
		src/ext/glm/core/type_vec2.hpp \
		src/ext/glm/core/type_vec2.inl \
		src/ext/glm/core/type_vec3.hpp \
		src/ext/glm/core/type_vec3.inl \
		src/ext/glm/core/type_vec4.hpp \
		src/ext/glm/core/type_vec4.inl \
		src/ext/glm/core/type_mat2x2.hpp \
		src/ext/glm/core/type_mat.hpp \
		src/ext/glm/core/type_mat2x2.inl \
		src/ext/glm/core/type_mat2x3.hpp \
		src/ext/glm/core/type_mat2x3.inl \
		src/ext/glm/core/type_mat2x4.hpp \
		src/ext/glm/core/type_mat2x4.inl \
		src/ext/glm/core/type_mat3x2.hpp \
		src/ext/glm/core/type_mat3x2.inl \
		src/ext/glm/core/type_mat3x3.hpp \
		src/ext/glm/core/type_mat3x3.inl \
		src/ext/glm/core/type_mat3x4.hpp \
		src/ext/glm/core/type_mat3x4.inl \
		src/ext/glm/core/type_mat4x2.hpp \
		src/ext/glm/core/type_mat4x2.inl \
		src/ext/glm/core/type_mat4x3.hpp \
		src/ext/glm/core/type_mat4x3.inl \
		src/ext/glm/core/type_mat4x4.hpp \
		src/ext/glm/core/type_mat4x4.inl \
		src/ext/glm/core/func_trigonometric.hpp \
		src/ext/glm/core/func_trigonometric.inl \
		src/ext/glm/core/_vectorize.hpp \
		src/ext/glm/core/func_exponential.hpp \
		src/ext/glm/core/func_exponential.inl \
		src/ext/glm/core/func_common.hpp \
		src/ext/glm/core/func_common.inl \
		src/ext/glm/core/func_packing.hpp \
		src/ext/glm/core/func_packing.inl \
		src/ext/glm/core/func_geometric.hpp \
		src/ext/glm/core/func_geometric.inl \
		src/ext/glm/core/func_matrix.hpp \
		src/ext/glm/core/func_matrix.inl \
		src/ext/glm/core/func_vector_relational.hpp \
		src/ext/glm/core/func_vector_relational.inl \
		src/ext/glm/core/func_integer.hpp \
		src/ext/glm/core/func_integer.inl \
		src/ext/glm/core/func_noise.hpp \
		src/ext/glm/core/func_noise.inl
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/Collision.o src/Collision.cpp

obj/CollisionMesh.o: src/CollisionMesh.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/CollisionMesh.o src/CollisionMesh.cpp

obj/FrameBuffer.o: src/FrameBuffer.cpp src/FrameBuffer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/FrameBuffer.o src/FrameBuffer.cpp

obj/Heightmap.o: src/Heightmap.cpp src/Heightmap.h \
		src/MeshObject.h \
		src/Types.h \
		src/Perlin.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/Heightmap.o src/Heightmap.cpp

obj/HeightNoise.o: src/HeightNoise.cpp src/HeightNoise.h \
		src/Perlin.h \
		src/VoxelCube.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/HeightNoise.o src/HeightNoise.cpp

obj/IEngine.o: src/IEngine.cpp src/IEngine.h \
		src/Shader.h \
		src/ObjectLoader.h \
		src/ImageLoader.h \
		src/World.h \
		src/Chunk.h \
		src/MeshObject.h \
		src/Types.h \
		src/Polygonize.h \
		src/VoxelCube.h \
		src/Vec3.h \
		src/MapGen.h \
		src/CaveNoise.h \
		src/Perlin.h \
		src/HeightNoise.h \
		src/PostProcess.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/IEngine.o src/IEngine.cpp

obj/ImageLoader.o: src/ImageLoader.cpp src/ImageLoader.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/ImageLoader.o src/ImageLoader.cpp

obj/main.o: src/main.cpp src/IEngine.h \
		src/Shader.h \
		src/ObjectLoader.h \
		src/ImageLoader.h \
		src/World.h \
		src/Chunk.h \
		src/MeshObject.h \
		src/Types.h \
		src/Polygonize.h \
		src/VoxelCube.h \
		src/Vec3.h \
		src/MapGen.h \
		src/CaveNoise.h \
		src/Perlin.h \
		src/HeightNoise.h \
		src/PostProcess.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/main.o src/main.cpp

obj/MapGen.o: src/MapGen.cpp src/MapGen.h \
		src/CaveNoise.h \
		src/Perlin.h \
		src/VoxelCube.h \
		src/HeightNoise.h \
		src/Types.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/MapGen.o src/MapGen.cpp

obj/MeshObject.o: src/MeshObject.cpp src/MeshObject.h \
		src/Types.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/MeshObject.o src/MeshObject.cpp

obj/Noise.o: src/Noise.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/Noise.o src/Noise.cpp

obj/ObjectLoader.o: src/ObjectLoader.cpp src/ObjectLoader.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/ObjectLoader.o src/ObjectLoader.cpp

obj/OCL3DFBMNoise.o: src/OCL3DFBMNoise.cpp src/OCL3DFBMNoise.h \
		src/OCLKernel.h \
		src/Types.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/OCL3DFBMNoise.o src/OCL3DFBMNoise.cpp

obj/OCLKernel.o: src/OCLKernel.cpp src/OCLKernel.h \
		src/Util.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/OCLKernel.o src/OCLKernel.cpp

obj/OCLMarchingCubes.o: src/OCLMarchingCubes.cpp src/OCLMarchingCubes.h \
		src/OCLKernel.h \
		src/Types.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/OCLMarchingCubes.o src/OCLMarchingCubes.cpp

obj/OCLNoise.o: src/OCLNoise.cpp src/OCLNoise.h \
		src/OCLKernel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/OCLNoise.o src/OCLNoise.cpp

obj/Perlin.o: src/Perlin.cpp src/Perlin.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/Perlin.o src/Perlin.cpp

obj/Polygonize.o: src/Polygonize.cpp src/Polygonize.h \
		src/MeshObject.h \
		src/Types.h \
		src/VoxelCube.h \
		src/Vec3.h \
		src/MCLookupTable.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/Polygonize.o src/Polygonize.cpp

obj/PostProcess.o: src/PostProcess.cpp src/PostProcess.h \
		src/Shader.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/PostProcess.o src/PostProcess.cpp

obj/Shader.o: src/Shader.cpp src/Shader.h \
		src/Util.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/Shader.o src/Shader.cpp

obj/shaderfuncs.o: src/shaderfuncs.cpp src/shaderfuncs.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/shaderfuncs.o src/shaderfuncs.cpp

obj/Text.o: src/Text.cpp src/Text.h \
		src/Shader.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/Text.o src/Text.cpp

obj/Texture.o: src/Texture.cpp src/Texture.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/Texture.o src/Texture.cpp

obj/Tree.o: src/Tree.cpp src/Tree.h \
		src/Types.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/Tree.o src/Tree.cpp

obj/Util.o: src/Util.cpp src/Util.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/Util.o src/Util.cpp

obj/Vec3.o: src/Vec3.cpp src/Vec3.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/Vec3.o src/Vec3.cpp

obj/VertexBufferObject.o: src/VertexBufferObject.cpp src/VertexBufferObject.h \
		src/Types.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/VertexBufferObject.o src/VertexBufferObject.cpp

obj/VoxelCube.o: src/VoxelCube.cpp src/VoxelCube.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/VoxelCube.o src/VoxelCube.cpp

obj/Water.o: src/Water.cpp src/Water.h \
		src/Vec3.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/Water.o src/Water.cpp

obj/World.o: src/World.cpp src/World.h \
		src/Chunk.h \
		src/MeshObject.h \
		src/Types.h \
		src/Polygonize.h \
		src/VoxelCube.h \
		src/Vec3.h \
		src/MapGen.h \
		src/CaveNoise.h \
		src/Perlin.h \
		src/HeightNoise.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/World.o src/World.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

